
modLoader="javafml" #mandatory

loaderVersion = "[47,)"

license = "All Rights Reserved"

[[mods]]
    modId="${mod_id}" #mandatory
    version="${mod_version}" #mandatory
    displayName="${mod_name}" #mandatory
    authors="${mod_authors}" #optional
    description='''Add fluid interraction from Alex's Caves block'''
    #logoFile="csnc.png" #optional
[[dependencies.${mod_id}]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1]"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.${mod_id}]]
    modId = "alexscaves"
    mandatory = true
    versionRange = "[2.0.2]"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.${mod_id}]]
    modId = "create"
    mandatory = true
    versionRange = "[6.0.4]"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.${mod_id}]]
    modId = "create_confectionery"
    mandatory = true
    versionRange = "[1.1.0]"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.${mod_id}]]
    modId = "create_things_and_misc"
    mandatory = true
    versionRange = "[1.0.0]"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.${mod_id}]]
    modId = "create_bic_bit"
    mandatory = true
    versionRange = "[1.0]"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.${mod_id}]]
    modId = "create_enchantment_industry"
    mandatory = true
    versionRange = "[1.3.2-for-create-6.0.4]"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.${mod_id}]]
    modId = "tconstruct"
    mandatory = true
    versionRange = "[3.10.0.67]"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory =true
    versionRange ="[47,)"
    ordering = "NONE"
    side = "BOTH"